apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: todo
  labels:
    app: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: todo-web
          image: sohail/todo-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: APPLICATION_URL
            valueFrom:
              configMapKeyRef:
                name: application-settings
                key: APPLICATION_URL
          - name: API_HOST
            valueFrom:
              configMapKeyRef:
                name: application-settings
                key: API_HOST
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-settings
  namespace: todo
data:
  APPLICATION_URL: todoapp.local
  API_HOST: todoapp.local/todos
  EMAIL: sotothehail@gmail.com
