apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    db: mongo
  name: mongo
spec:
  template:
    metadata:
      labels:
        db: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          name: driver
        volumeMounts:
        - mountPath: /data/db
          name: mongo-fs-storage
      volumes:
      - name: mongo-fs-storage
        emptyDir: {}