apiVersion: v1
kind: ConfigMap
metadata:
  name: application-settings
  namespace: todo
data:
  APPLICATION_URL: todoapp.local
  API_HOST: todoapp.local/todos
  EMAIL: sotothehail@gmail.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  hsts-include-subdomains: "false"
  body-size: "64m"
  server-name-hash-bucket-size: "256"
  log-format-upstream: '{ "time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
    "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$request_id", "remote_user":
    "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status":
    $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri",
    "request_query": "$args", "request_length": $request_length, "duration": $request_time,
    "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent":
    "$http_user_agent" }'
