apiVersion: v1
kind: Namespace
metadata:
  name: todo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-settings
  namespace: todo
data:
  APPLICATION_URL: todoapp.local
  API_HOST: todoapp.local/todos
  EMAIL: sotothehail@gmail.com