apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: web-v000
  namespace: todo
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: todo-web
          image: sohail/todo-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: APPLICATION_URL
            valueFrom:
              configMapKeyRef:
                name: application-settings
                key: APPLICATION_URL
          - name: API_HOST
            valueFrom:
              configMapKeyRef:
                name: application-settings
                key: API_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: todo
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  namespace: todo
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - todoapp.local
    secretName: ingress-tls-secret
  rules:
  - host: todoapp.local
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
      - path: /todos
        backend:
          serviceName: api
          servicePort: 3000