apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: api-v000
  namespace: todo
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: todo-api
          image: sohail/todo-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
          - name: MONGODB_HOST
            value: mongodb-host
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: todo
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
